name: Greetings

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    
      - shell: bash
      - if: ${{ commits[after][message] != 'nightly build through appveyor' }}
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users first issue'
