name: Greetings

on: 
    schedule:
      - cron: '20 4 * * *'
    workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
        - name: Webhook
          uses: joelwmale/webhook-action@master
          with:
                url: ${{ secrets.WEBHOOK_URL }}
                headers: '{"repository": "joelwmale/webhook-action"}'
                body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
